[package]
name = "rsytrace"
version = "0.1.0"
authors = ["EliseZeroTwo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
rand = { version = "0.8.0", features = ["small_rng", "std", "std_rng"] }  